"""redesign: 3 categories, headline stats, routine, goal image, history summary

Revision ID: 1649e64384b7
Revises: 73c4a1906885
Create Date: 2026-06-25 15:19:05.454362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1649e64384b7'
down_revision: Union[str, Sequence[str], None] = '73c4a1906885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_summaries',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('analysis_reports', sa.Column('headline_stats', sa.JSON(), nullable=True))
    op.add_column('analysis_reports', sa.Column('recommended_routine', sa.JSON(), nullable=True))
    op.add_column('body_goals', sa.Column('reference_image_consent', sa.Boolean(), nullable=False, server_default=sa.false()))
    # sqlite는 ALTER COLUMN TYPE을 지원하지 않아 batch 모드(테이블 재생성 방식)로 처리
    with op.batch_alter_table('body_scan_sessions') as batch_op:
        batch_op.alter_column('category',
                   existing_type=sa.VARCHAR(length=11),
                   type_=sa.Enum('full_body', 'upper', 'lower', name='scancategory'),
                   existing_nullable=False)
    op.add_column('exercises', sa.Column('youtube_video_ids', sa.JSON(), nullable=False, server_default='[]'))
    op.drop_column('exercises', 'youtube_video_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('youtube_video_id', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('exercises', 'youtube_video_ids')
    op.alter_column('body_scan_sessions', 'category',
               existing_type=sa.Enum('full_body', 'upper', 'lower', name='scancategory'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.drop_column('body_goals', 'reference_image_consent')
    op.drop_column('analysis_reports', 'recommended_routine')
    op.drop_column('analysis_reports', 'headline_stats')
    op.drop_table('history_summaries')
    # ### end Alembic commands ###
