"""add quota events and error message

Revision ID: 73c4a1906885
Revises: c909d49b0470
Create Date: 2026-06-23 19:05:36.856719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73c4a1906885'
down_revision: Union[str, Sequence[str], None] = 'c909d49b0470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_quota_events',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.Enum('rate_limit', 'daily_quota_exceeded', name='quotaeventtype'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('body_scan_sessions', sa.Column('error_message', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('body_scan_sessions', 'error_message')
    op.drop_table('api_quota_events')
    # ### end Alembic commands ###
