"""init schema

Revision ID: c909d49b0470
Revises: 
Create Date: 2026-06-23 18:00:57.302357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c909d49b0470'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ko', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('primary_muscles', sa.JSON(), nullable=False),
    sa.Column('secondary_muscles', sa.JSON(), nullable=False),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('image_paths', sa.JSON(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=50), nullable=True),
    sa.Column('youtube_channel_verified', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('free_exercise_db', 'ai_generated', 'curated', name='exercisesource'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_external_id'), 'exercises', ['external_id'], unique=False)
    op.create_table('routines',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_body_parts', sa.JSON(), nullable=False),
    sa.Column('goal_tags', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('exercise_sequence', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('is_minor', sa.Boolean(), nullable=False),
    sa.Column('guardian_consent_status', sa.Enum('na', 'pending', 'approved', 'rejected', name='guardianconsentstatus'), nullable=False),
    sa.Column('guardian_email', sa.String(length=255), nullable=True),
    sa.Column('guardian_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_retention_until', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('body_goals',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_type', sa.Enum('text', 'reference_image', name='goaltype'), nullable=False),
    sa.Column('goal_text', sa.Text(), nullable=True),
    sa.Column('reference_image_path', sa.String(length=500), nullable=True),
    sa.Column('target_body_parts', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('body_image_consents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('consent_type', sa.Enum('camera_and_body_image', 'analysis', 'storage', name='bodyimageconsenttype'), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('body_scan_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scan_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.Enum('full_360', 'upper_front', 'upper_back', 'lower', 'custom', name='scancategory'), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'completed', 'failed', name='scanstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_consents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('policy_type', sa.Enum('terms_of_service', 'privacy_policy', 'marketing_optional', name='policytype'), nullable=False),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('consented', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_reports',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('weak_points', sa.JSON(), nullable=False),
    sa.Column('recommended_exercise_ids', sa.JSON(), nullable=False),
    sa.Column('goal_comparison', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['body_scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('body_scan_images',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('angle', sa.Enum('front', 'back', 'side', 'upper', 'lower', name='imageangle'), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['body_scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scan_session_id', sa.Uuid(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scan_session_id'], ['body_scan_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vision_analysis',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('body_part_assessment', sa.JSON(), nullable=False),
    sa.Column('overall_comment', sa.Text(), nullable=False),
    sa.Column('disclaimer_shown', sa.Boolean(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['body_scan_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pose_metrics',
    sa.Column('scan_image_id', sa.Uuid(), nullable=False),
    sa.Column('landmarks_json', sa.JSON(), nullable=False),
    sa.Column('shoulder_width_ratio', sa.Float(), nullable=True),
    sa.Column('waist_hip_ratio', sa.Float(), nullable=True),
    sa.Column('limb_symmetry_score', sa.Float(), nullable=True),
    sa.Column('posture_flags', sa.JSON(), nullable=True),
    sa.Column('raw_confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scan_image_id'], ['body_scan_images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_routine_assignments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('routine_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'skipped', name='routineassignmentstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['analysis_reports.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_routine_assignments')
    op.drop_table('pose_metrics')
    op.drop_table('vision_analysis')
    op.drop_table('progress_logs')
    op.drop_table('body_scan_images')
    op.drop_table('analysis_reports')
    op.drop_table('policy_consents')
    op.drop_table('body_scan_sessions')
    op.drop_table('body_image_consents')
    op.drop_table('body_goals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('routines')
    op.drop_index(op.f('ix_exercises_external_id'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
